apiVersion: config.kueue.x-k8s.io/v1alpha1
kind: Configuration
health:
  healthProbeBindAddress: :8081
metrics:
  bindAddress: :8080
webhook:
  port: 9443
leaderElection:
  leaderElect: true
  resourceName: c1f6bfd2.kueue.x-k8s.io
#manageJobsWithoutQueueName: true
