# permissions for end users to view queues.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: queue-viewer-role
  labels:
    rbac.kueue.x-k8s.io/batch-admin: "true"
    rbac.kueue.x-k8s.io/batch-user: "true"
rules:
- apiGroups:
  - kueue.x-k8s.io
  resources:
  - queues
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - kueue.x-k8s.io
  resources:
  - queues/status
  verbs:
  - get
